import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class CountriesServiceService {

  listOfCountries = [
        {name: 'Afghanistan', code: 'AF', flag: 'https://www.countryflags.io/af/flat/64.png'},
        {name: 'Åland Islands', code: 'AX', flag: 'https://www.countryflags.io/ax/flat/64.png'},
        {name: 'Albania', code: 'AL', flag: 'https://www.countryflags.io/al/flat/64.png'},
        {name: 'Algeria', code: 'DZ', flag: 'https://www.countryflags.io/dz/flat/64.png'},
        {name: 'American Samoa', code: 'AS', flag: 'https://www.countryflags.io/as/flat/64.png'},
        {name: 'AndorrA', code: 'AD', flag: 'https://www.countryflags.io/ad/flat/64.png'},
        {name: 'Angola', code: 'AO', flag: 'https://www.countryflags.io/ao/flat/64.png'},
        {name: 'Anguilla', code: 'AI', flag: 'https://www.countryflags.io/ai/flat/64.png'},
        {name: 'Antarctica', code: 'AQ', flag: 'https://www.countryflags.io/aq/flat/64.png'},
        {name: 'Antigua and Barbuda', code: 'AG', flag: 'https://www.countryflags.io/ag/flat/64.png'},
        {name: 'Argentina', code: 'AR', flag: 'https://www.countryflags.io/ar/flat/64.png'},
        {name: 'Armenia', code: 'AM', flag: 'https://www.countryflags.io/am/flat/64.png'},
        {name: 'Aruba', code: 'AW', flag: 'https://www.countryflags.io/aw/flat/64.png'},
        {name: 'Australia', code: 'AU', flag: 'https://www.countryflags.io/au/flat/64.png'},
        {name: 'Austria', code: 'AT', flag: 'https://www.countryflags.io/at/flat/64.png'},
        {name: 'Azerbaijan', code: 'AZ', flag: 'https://www.countryflags.io/az/flat/64.png'},
        {name: 'Bahamas', code: 'BS', flag: 'https://www.countryflags.io/bs/flat/64.png'},
        {name: 'Bahrain', code: 'BH', flag: 'https://www.countryflags.io/bh/flat/64.png'},
        {name: 'Bangladesh', code: 'BD', flag: 'https://www.countryflags.io/bd/flat/64.png'},
        {name: 'Barbados', code: 'BB', flag: 'https://www.countryflags.io/bb/flat/64.png'},
        {name: 'Belarus', code: 'BY', flag: 'https://www.countryflags.io/by/flat/64.png'},
        {name: 'Belgium', code: 'BE', flag: 'https://www.countryflags.io/be/flat/64.png'},
        {name: 'Belize', code: 'BZ', flag: 'https://www.countryflags.io/bz/flat/64.png'},
        {name: 'Benin', code: 'BJ', flag: 'https://www.countryflags.io/bj/flat/64.png'},
        {name: 'Bermuda', code: 'BM', flag: 'https://www.countryflags.io/bm/flat/64.png'},
        {name: 'Bhutan', code: 'BT', flag: 'https://www.countryflags.io/bt/flat/64.png'},
        {name: 'Bolivia', code: 'BO', flag: 'https://www.countryflags.io/bo/flat/64.png'},
        {name: 'Bosnia and Herzegovina', code: 'BA', flag: 'https://www.countryflags.io/ba/flat/64.png'},
        {name: 'Botswana', code: 'BW', flag: 'https://www.countryflags.io/bw/flat/64.png'},
        {name: 'Bouvet Island', code: 'BV', flag: 'https://www.countryflags.io/bv/flat/64.png'},
        {name: 'Brazil', code: 'BR', flag: 'https://www.countryflags.io/br/flat/64.png'},
        {name: 'British Indian Ocean Territory', code: 'IO', flag: 'https://www.countryflags.io/io/flat/64.png'},
        {name: 'Brunei Darussalam', code: 'BN', flag: 'https://www.countryflags.io/bn/flat/64.png'},
        {name: 'Bulgaria', code: 'BG', flag: 'https://www.countryflags.io/bg/flat/64.png'},
        {name: 'Burkina Faso', code: 'BF', flag: 'https://www.countryflags.io/bf/flat/64.png'},
        {name: 'Burundi', code: 'BI', flag: 'https://www.countryflags.io/bi/flat/64.png'},
        {name: 'Cambodia', code: 'KH', flag: 'https://www.countryflags.io/kh/flat/64.png'},
        {name: 'Cameroon', code: 'CM', flag: 'https://www.countryflags.io/cm/flat/64.png'},
        {name: 'Canada', code: 'CA', flag: 'https://www.countryflags.io/ca/flat/64.png'},
        {name: 'Cape Verde', code: 'CV', flag: 'https://www.countryflags.io/cv/flat/64.png'},
        {name: 'Cayman Islands', code: 'KY', flag: 'https://www.countryflags.io/ky/flat/64.png'},
        {name: 'Central African Republic', code: 'CF', flag: 'https://www.countryflags.io/cf/flat/64.png'},
        {name: 'Chad', code: 'TD', flag: 'https://www.countryflags.io/td/flat/64.png'},
        {name: 'Chile', code: 'CL', flag: 'https://www.countryflags.io/cl/flat/64.png'},
        {name: 'China', code: 'CN', flag: 'https://www.countryflags.io/cn/flat/64.png'},
        {name: 'Christmas Island', code: 'CX', flag: 'https://www.countryflags.io/cx/flat/64.png'},
        {name: 'Cocos (Keeling) Islands', code: 'CC', flag: 'https://www.countryflags.io/cc/flat/64.png'},
        {name: 'Colombia', code: 'CO', flag: 'https://www.countryflags.io/co/flat/64.png'},
        {name: 'Comoros', code: 'KM', flag: 'https://www.countryflags.io/km/flat/64.png'},
        {name: 'Congo', code: 'CG', flag: 'https://www.countryflags.io/cg/flat/64.png'},
        {name: 'Congo, The Democratic Republic of the', code: 'CD', flag: 'https://www.countryflags.io/cd/flat/64.png'},
        {name: 'Cook Islands', code: 'CK', flag: 'https://www.countryflags.io/ck/flat/64.png'},
        {name: 'Costa Rica', code: 'CR', flag: 'https://www.countryflags.io/cr/flat/64.png'},
        {name: 'Cote D\'Ivoire', code: 'CI', flag: 'https://www.countryflags.io/ci/flat/64.png'},
        {name: 'Croatia', code: 'HR', flag: 'https://www.countryflags.io/hr/flat/64.png'},
        {name: 'Cuba', code: 'CU', flag: 'https://www.countryflags.io/cu/flat/64.png'},
        {name: 'Cyprus', code: 'CY', flag: 'https://www.countryflags.io/cy/flat/64.png'},
        {name: 'Czech Republic', code: 'CZ', flag: 'https://www.countryflags.io/cz/flat/64.png'},
        {name: 'Denmark', code: 'DK', flag: 'https://www.countryflags.io/dk/flat/64.png'},
        {name: 'Djibouti', code: 'DJ', flag: 'https://www.countryflags.io/dj/flat/64.png'},
        {name: 'Dominica', code: 'DM', flag: 'https://www.countryflags.io/dm/flat/64.png'},
        {name: 'Dominican Republic', code: 'DO', flag: 'https://www.countryflags.io/do/flat/64.png'},
        {name: 'Ecuador', code: 'EC', flag: 'https://www.countryflags.io/ec/flat/64.png'},
        {name: 'Egypt', code: 'EG', flag: 'https://www.countryflags.io/eg/flat/64.png'},
        {name: 'El Salvador', code: 'SV', flag: 'https://www.countryflags.io/sv/flat/64.png'},
        {name: 'Equatorial Guinea', code: 'GQ', flag: 'https://www.countryflags.io/gq/flat/64.png'},
        {name: 'Eritrea', code: 'ER', flag: 'https://www.countryflags.io/er/flat/64.png'},
        {name: 'Estonia', code: 'EE', flag: 'https://www.countryflags.io/ee/flat/64.png'},
        {name: 'Ethiopia', code: 'ET', flag: 'https://www.countryflags.io/et/flat/64.png'},
        {name: 'Falkland Islands (Malvinas)', code: 'FK', flag: 'https://www.countryflags.io/fk/flat/64.png'},
        {name: 'Faroe Islands', code: 'FO', flag: 'https://www.countryflags.io/fo/flat/64.png'},
        {name: 'Fiji', code: 'FJ', flag: 'https://www.countryflags.io/fj/flat/64.png'},
        {name: 'Finland', code: 'FI', flag: 'https://www.countryflags.io/fi/flat/64.png'},
        {name: 'France', code: 'FR', flag: 'https://www.countryflags.io/fr/flat/64.png'},
        {name: 'French Guiana', code: 'GF', flag: 'https://www.countryflags.io/gf/flat/64.png'},
        {name: 'French Polynesia', code: 'PF', flag: 'https://www.countryflags.io/pf/flat/64.png'},
        {name: 'French Southern Territories', code: 'TF', flag: 'https://www.countryflags.io/tf/flat/64.png'},
        {name: 'Gabon', code: 'GA', flag: 'https://www.countryflags.io/ga/flat/64.png'},
        {name: 'Gambia', code: 'GM', flag: 'https://www.countryflags.io/gm/flat/64.png'},
        {name: 'Georgia', code: 'GE', flag: 'https://www.countryflags.io/ge/flat/64.png'},
        {name: 'Germany', code: 'DE', flag: 'https://www.countryflags.io/de/flat/64.png'},
        {name: 'Ghana', code: 'GH', flag: 'https://www.countryflags.io/gh/flat/64.png'},
        {name: 'Gibraltar', code: 'GI', flag: 'https://www.countryflags.io/gi/flat/64.png'},
        {name: 'Greece', code: 'GR', flag: 'https://www.countryflags.io/gr/flat/64.png'},
        {name: 'Greenland', code: 'GL', flag: 'https://www.countryflags.io/gl/flat/64.png'},
        {name: 'Grenada', code: 'GD', flag: 'https://www.countryflags.io/gd/flat/64.png'},
        {name: 'Guadeloupe', code: 'GP', flag: 'https://www.countryflags.io/gp/flat/64.png'},
        {name: 'Guam', code: 'GU', flag: 'https://www.countryflags.io/gu/flat/64.png'},
        {name: 'Guatemala', code: 'GT', flag: 'https://www.countryflags.io/gt/flat/64.png'},
        {name: 'Guernsey', code: 'GG', flag: 'https://www.countryflags.io/gg/flat/64.png'},
        {name: 'Guinea', code: 'GN', flag: 'https://www.countryflags.io/gn/flat/64.png'},
        {name: 'Guinea-Bissau', code: 'GW', flag: 'https://www.countryflags.io/gw/flat/64.png'},
        {name: 'Guyana', code: 'GY', flag: 'https://www.countryflags.io/gy/flat/64.png'},
        {name: 'Haiti', code: 'HT', flag: 'https://www.countryflags.io/ht/flat/64.png'},
        {name: 'Heard Island and Mcdonald Islands', code: 'HM', flag: 'https://www.countryflags.io/hm/flat/64.png'},
        {name: 'Holy See (Vatican City State)', code: 'VA', flag: 'https://www.countryflags.io/va/flat/64.png'},
        {name: 'Honduras', code: 'HN', flag: 'https://www.countryflags.io/hn/flat/64.png'},
        {name: 'Hong Kong', code: 'HK', flag: 'https://www.countryflags.io/hk/flat/64.png'},
        {name: 'Hungary', code: 'HU', flag: 'https://www.countryflags.io/hu/flat/64.png'},
        {name: 'Iceland', code: 'IS', flag: 'https://www.countryflags.io/is/flat/64.png'},
        {name: 'India', code: 'IN', flag: 'https://www.countryflags.io/in/flat/64.png'},
        {name: 'Indonesia', code: 'ID', flag: 'https://www.countryflags.io/id/flat/64.png'},
        {name: 'Iran, Islamic Republic Of', code: 'IR', flag: 'https://www.countryflags.io/ir/flat/64.png'},
        {name: 'Iraq', code: 'IQ', flag: 'https://www.countryflags.io/iq/flat/64.png'},
        {name: 'Ireland', code: 'IE', flag: 'https://www.countryflags.io/ie/flat/64.png'},
        {name: 'Isle of Man', code: 'IM', flag: 'https://www.countryflags.io/im/flat/64.png'},
        {name: 'Israel', code: 'IL', flag: 'https://www.countryflags.io/il/flat/64.png'},
        {name: 'Italy', code: 'IT', flag: 'https://www.countryflags.io/it/flat/64.png'},
        {name: 'Jamaica', code: 'JM', flag: 'https://www.countryflags.io/jm/flat/64.png'},
        {name: 'Japan', code: 'JP', flag: 'https://www.countryflags.io/jp/flat/64.png'},
        {name: 'Jersey', code: 'JE', flag: 'https://www.countryflags.io/je/flat/64.png'},
        {name: 'Jordan', code: 'JO', flag: 'https://www.countryflags.io/jo/flat/64.png'},
        {name: 'Kazakhstan', code: 'KZ', flag: 'https://www.countryflags.io/kz/flat/64.png'},
        {name: 'Kosovo', code: 'XK', flag: 'https://www.countryflags.io/xk/flat/64.png'},
        {name: 'Kenya', code: 'KE', flag: 'https://www.countryflags.io/ke/flat/64.png'},
        {name: 'Kiribati', code: 'KI', flag: 'https://www.countryflags.io/ki/flat/64.png'},
        {name: 'Korea, Democratic People\'S Republic of', code: 'KP', flag: 'https://www.countryflags.io/kp/flat/64.png'},
        {name: 'Korea, Republic of', code: 'KR', flag: 'https://www.countryflags.io/kr/flat/64.png'},
        {name: 'Kuwait', code: 'KW', flag: 'https://www.countryflags.io/kw/flat/64.png'},
        {name: 'Kyrgyzstan', code: 'KG', flag: 'https://www.countryflags.io/kg/flat/64.png'},
        {name: 'Lao People\'S Democratic Republic', code: 'LA', flag: 'https://www.countryflags.io/la/flat/64.png'},
        {name: 'Latvia', code: 'LV', flag: 'https://www.countryflags.io/lv/flat/64.png'},
        {name: 'Lebanon', code: 'LB', flag: 'https://www.countryflags.io/lb/flat/64.png'},
        {name: 'Lesotho', code: 'LS', flag: 'https://www.countryflags.io/ls/flat/64.png'},
        {name: 'Liberia', code: 'LR', flag: 'https://www.countryflags.io/lr/flat/64.png'},
        {name: 'Libyan Arab Jamahiriya', code: 'LY', flag: 'https://www.countryflags.io/ly/flat/64.png'},
        {name: 'Liechtenstein', code: 'LI', flag: 'https://www.countryflags.io/li/flat/64.png'},
        {name: 'Lithuania', code: 'LT', flag: 'https://www.countryflags.io/lt/flat/64.png'},
        {name: 'Luxembourg', code: 'LU', flag: 'https://www.countryflags.io/lu/flat/64.png'},
        {name: 'Macao', code: 'MO', flag: 'https://www.countryflags.io/mo/flat/64.png'},
        {name: 'Macedonia, The Former Yugoslav Republic of', code: 'MK', flag: 'https://www.countryflags.io/mk/flat/64.png'},
        {name: 'Madagascar', code: 'MG', flag: 'https://www.countryflags.io/mg/flat/64.png'},
        {name: 'Malawi', code: 'MW', flag: 'https://www.countryflags.io/mw/flat/64.png'},
        {name: 'Malaysia', code: 'MY', flag: 'https://www.countryflags.io/my/flat/64.png'},
        {name: 'Maldives', code: 'MV', flag: 'https://www.countryflags.io/mv/flat/64.png'},
        {name: 'Mali', code: 'ML', flag: 'https://www.countryflags.io/ml/flat/64.png'},
        {name: 'Malta', code: 'MT', flag: 'https://www.countryflags.io/mt/flat/64.png'},
        {name: 'Marshall Islands', code: 'MH', flag: 'https://www.countryflags.io/mh/flat/64.png'},
        {name: 'Martinique', code: 'MQ', flag: 'https://www.countryflags.io/mq/flat/64.png'},
        {name: 'Mauritania', code: 'MR', flag: 'https://www.countryflags.io/mr/flat/64.png'},
        {name: 'Mauritius', code: 'MU', flag: 'https://www.countryflags.io/mu/flat/64.png'},
        {name: 'Mayotte', code: 'YT', flag: 'https://www.countryflags.io/yt/flat/64.png'},
        {name: 'Mexico', code: 'MX', flag: 'https://www.countryflags.io/mx/flat/64.png'},
        {name: 'Micronesia, Federated States of', code: 'FM', flag: 'https://www.countryflags.io/fm/flat/64.png'},
        {name: 'Moldova, Republic of', code: 'MD', flag: 'https://www.countryflags.io/md/flat/64.png'},
        {name: 'Monaco', code: 'MC', flag: 'https://www.countryflags.io/mc/flat/64.png'},
        {name: 'Mongolia', code: 'MN', flag: 'https://www.countryflags.io/mn/flat/64.png'},
        {name: 'Montserrat', code: 'MS', flag: 'https://www.countryflags.io/ms/flat/64.png'},
        {name: 'Morocco', code: 'MA', flag: 'https://www.countryflags.io/ma/flat/64.png'},
        {name: 'Mozambique', code: 'MZ', flag: 'https://www.countryflags.io/mz/flat/64.png'},
        {name: 'Myanmar', code: 'MM', flag: 'https://www.countryflags.io/mm/flat/64.png'},
        {name: 'Namibia', code: 'NA', flag: 'https://www.countryflags.io/na/flat/64.png'},
        {name: 'Nauru', code: 'NR', flag: 'https://www.countryflags.io/nr/flat/64.png'},
        {name: 'Nepal', code: 'NP', flag: 'https://www.countryflags.io/np/flat/64.png'},
        {name: 'Netherlands', code: 'NL', flag: 'https://www.countryflags.io/nl/flat/64.png'},
        {name: 'Netherlands Antilles', code: 'AN', flag: 'https://www.countryflags.io/an/flat/64.png'},
        {name: 'New Caledonia', code: 'NC', flag: 'https://www.countryflags.io/nc/flat/64.png'},
        {name: 'New Zealand', code: 'NZ', flag: 'https://www.countryflags.io/nz/flat/64.png'},
        {name: 'Nicaragua', code: 'NI', flag: 'https://www.countryflags.io/ni/flat/64.png'},
        {name: 'Niger', code: 'NE', flag: 'https://www.countryflags.io/ne/flat/64.png'},
        {name: 'Nigeria', code: 'NG', flag: 'https://www.countryflags.io/ng/flat/64.png'},
        {name: 'Niue', code: 'NU', flag: 'https://www.countryflags.io/nu/flat/64.png'},
        {name: 'Norfolk Island', code: 'NF', flag: 'https://www.countryflags.io/nf/flat/64.png'},
        {name: 'Northern Mariana Islands', code: 'MP', flag: 'https://www.countryflags.io/mp/flat/64.png'},
        {name: 'Norway', code: 'NO', flag: 'https://www.countryflags.io/no/flat/64.png'},
        {name: 'Oman', code: 'OM', flag: 'https://www.countryflags.io/om/flat/64.png'},
        {name: 'Pakistan', code: 'PK', flag: 'https://www.countryflags.io/pk/flat/64.png'},
        {name: 'Palau', code: 'PW', flag: 'https://www.countryflags.io/pw/flat/64.png'},
        {name: 'Palestinian Territory, Occupied', code: 'PS', flag: 'https://www.countryflags.io/ps/flat/64.png'},
        {name: 'Panama', code: 'PA', flag: 'https://www.countryflags.io/pa/flat/64.png'},
        {name: 'Papua New Guinea', code: 'PG', flag: 'https://www.countryflags.io/pg/flat/64.png'},
        {name: 'Paraguay', code: 'PY', flag: 'https://www.countryflags.io/py/flat/64.png'},
        {name: 'Peru', code: 'PE', flag: 'https://www.countryflags.io/pe/flat/64.png'},
        {name: 'Philippines', code: 'PH', flag: 'https://www.countryflags.io/ph/flat/64.png'},
        {name: 'Pitcairn', code: 'PN', flag: 'https://www.countryflags.io/pn/flat/64.png'},
        {name: 'Poland', code: 'PL', flag: 'https://www.countryflags.io/pl/flat/64.png'},
        {name: 'Portugal', code: 'PT', flag: 'https://www.countryflags.io/pt/flat/64.png'},
        {name: 'Puerto Rico', code: 'PR', flag: 'https://www.countryflags.io/pr/flat/64.png'},
        {name: 'Qatar', code: 'QA', flag: 'https://www.countryflags.io/qa/flat/64.png'},
        {name: 'Reunion', code: 'RE', flag: 'https://www.countryflags.io/re/flat/64.png'},
        {name: 'Romania', code: 'RO', flag: 'https://www.countryflags.io/ro/flat/64.png'},
        {name: 'Russian Federation', code: 'RU', flag: 'https://www.countryflags.io/ru/flat/64.png'},
        {name: 'RWANDA', code: 'RW', flag: 'https://www.countryflags.io/rw/flat/64.png'},
        {name: 'Saint Helena', code: 'SH', flag: 'https://www.countryflags.io/sh/flat/64.png'},
        {name: 'Saint Kitts and Nevis', code: 'KN', flag: 'https://www.countryflags.io/kn/flat/64.png'},
        {name: 'Saint Lucia', code: 'LC', flag: 'https://www.countryflags.io/lc/flat/64.png'},
        {name: 'Saint Pierre and Miquelon', code: 'PM', flag: 'https://www.countryflags.io/pm/flat/64.png'},
        {name: 'Saint Vincent and the Grenadines', code: 'VC', flag: 'https://www.countryflags.io/vc/flat/64.png'},
        {name: 'Samoa', code: 'WS', flag: 'https://www.countryflags.io/ws/flat/64.png'},
        {name: 'San Marino', code: 'SM', flag: 'https://www.countryflags.io/sm/flat/64.png'},
        {name: 'Sao Tome and Principe', code: 'ST', flag: 'https://www.countryflags.io/st/flat/64.png'},
        {name: 'Saudi Arabia', code: 'SA', flag: 'https://www.countryflags.io/sa/flat/64.png'},
        {name: 'Senegal', code: 'SN', flag: 'https://www.countryflags.io/sn/flat/64.png'},
        {name: 'Serbia', code: 'RS', flag: 'https://www.countryflags.io/rs/flat/64.png'},
        {name: 'Montenegro', code: 'ME', flag: 'https://www.countryflags.io/me/flat/64.png'},
        {name: 'Seychelles', code: 'SC', flag: 'https://www.countryflags.io/sc/flat/64.png'},
        {name: 'Sierra Leone', code: 'SL', flag: 'https://www.countryflags.io/sl/flat/64.png'},
        {name: 'Singapore', code: 'SG', flag: 'https://www.countryflags.io/sg/flat/64.png'},
        {name: 'Slovakia', code: 'SK', flag: 'https://www.countryflags.io/sk/flat/64.png'},
        {name: 'Slovenia', code: 'SI', flag: 'https://www.countryflags.io/si/flat/64.png'},
        {name: 'Solomon Islands', code: 'SB', flag: 'https://www.countryflags.io/sb/flat/64.png'},
        {name: 'Somalia', code: 'SO', flag: 'https://www.countryflags.io/so/flat/64.png'},
        {name: 'South Africa', code: 'ZA', flag: 'https://www.countryflags.io/za/flat/64.png'},
        {name: 'South Georgia and the South Sandwich Islands', code: 'GS', flag: 'https://www.countryflags.io/gs/flat/64.png'},
        {name: 'Spain', code: 'ES', flag: 'https://www.countryflags.io/es/flat/64.png'},
        {name: 'Sri Lanka', code: 'LK', flag: 'https://www.countryflags.io/lk/flat/64.png'},
        {name: 'Sudan', code: 'SD', flag: 'https://www.countryflags.io/sd/flat/64.png'},
        {name: 'Suriname', code: 'SR', flag: 'https://www.countryflags.io/sr/flat/64.png'},
        {name: 'Svalbard and Jan Mayen', code: 'SJ', flag: 'https://www.countryflags.io/sj/flat/64.png'},
        {name: 'Swaziland', code: 'SZ', flag: 'https://www.countryflags.io/sz/flat/64.png'},
        {name: 'Sweden', code: 'SE', flag: 'https://www.countryflags.io/se/flat/64.png'},
        {name: 'Switzerland', code: 'CH', flag: 'https://www.countryflags.io/ch/flat/64.png'},
        {name: 'Syrian Arab Republic', code: 'SY', flag: 'https://www.countryflags.io/sy/flat/64.png'},
        {name: 'Taiwan, Province of China', code: 'TW', flag: 'https://www.countryflags.io/tw/flat/64.png'},
        {name: 'Tajikistan', code: 'TJ', flag: 'https://www.countryflags.io/tj/flat/64.png'},
        {name: 'Tanzania, United Republic of', code: 'TZ', flag: 'https://www.countryflags.io/tz/flat/64.png'},
        {name: 'Thailand', code: 'TH', flag: 'https://www.countryflags.io/th/flat/64.png'},
        {name: 'Timor-Leste', code: 'TL', flag: 'https://www.countryflags.io/tl/flat/64.png'},
        {name: 'Togo', code: 'TG', flag: 'https://www.countryflags.io/tg/flat/64.png'},
        {name: 'Tokelau', code: 'TK', flag: 'https://www.countryflags.io/tk/flat/64.png'},
        {name: 'Tonga', code: 'TO', flag: 'https://www.countryflags.io/to/flat/64.png'},
        {name: 'Trinidad and Tobago', code: 'TT', flag: 'https://www.countryflags.io/tt/flat/64.png'},
        {name: 'Tunisia', code: 'TN', flag: 'https://www.countryflags.io/tn/flat/64.png'},
        {name: 'Turkey', code: 'TR', flag: 'https://www.countryflags.io/tr/flat/64.png'},
        {name: 'Turkmenistan', code: 'TM', flag: 'https://www.countryflags.io/tm/flat/64.png'},
        {name: 'Turks and Caicos Islands', code: 'TC', flag: 'https://www.countryflags.io/tc/flat/64.png'},
        {name: 'Tuvalu', code: 'TV', flag: 'https://www.countryflags.io/tv/flat/64.png'},
        {name: 'Uganda', code: 'UG', flag: 'https://www.countryflags.io/ug/flat/64.png'},
        {name: 'Ukraine', code: 'UA', flag: 'https://www.countryflags.io/ua/flat/64.png'},
        {name: 'United Arab Emirates', code: 'AE', flag: 'https://www.countryflags.io/ae/flat/64.png'},
        {name: 'United Kingdom', code: 'GB', flag: 'https://www.countryflags.io/gb/flat/64.png'},
        {name: 'United States', code: 'US', flag: 'https://www.countryflags.io/us/flat/64.png'},
        {name: 'United States Minor Outlying Islands', code: 'UM', flag: 'https://www.countryflags.io/um/flat/64.png'},
        {name: 'Uruguay', code: 'UY', flag: 'https://www.countryflags.io/uy/flat/64.png'},
        {name: 'Uzbekistan', code: 'UZ', flag: 'https://www.countryflags.io/uz/flat/64.png'},
        {name: 'Vanuatu', code: 'VU', flag: 'https://www.countryflags.io/vu/flat/64.png'},
        {name: 'Venezuela', code: 'VE', flag: 'https://www.countryflags.io/ve/flat/64.png'},
        {name: 'Viet Nam', code: 'VN', flag: 'https://www.countryflags.io/vn/flat/64.png'},
        {name: 'Virgin Islands, British', code: 'VG', flag: 'https://www.countryflags.io/vg/flat/64.png'},
        {name: 'Virgin Islands, U.S.', code: 'VI', flag: 'https://www.countryflags.io/vi/flat/64.png'},
        {name: 'Wallis and Futuna', code: 'WF', flag: 'https://www.countryflags.io/wf/flat/64.png'},
        {name: 'Western Sahara', code: 'EH', flag: 'https://www.countryflags.io/eh/flat/64.png'},
        {name: 'Yemen', code: 'YE', flag: 'https://www.countryflags.io/ye/flat/64.png'},
        {name: 'Zambia', code: 'ZM', flag: 'https://www.countryflags.io/zm/flat/64.png'},
        {name: 'Zimbabwe', code: 'ZW', flag: 'https://www.countryflags.io/zw/flat/64.png'}
    ];

  constructor() { }

  getAllCountries() {
    return this.listOfCountries;
  }
}
